### ISSUE TITLE
脚本有错误

### ISSUE THREAD

**Issue by timelock66** [qimu666/xiaoyuankosuan#1]
23:10:10.574 Traceback (most recent call last):
23:10:10.575   File "main.py", line 45, in <module>
    main()
    ~~~~^^
23:10:10.575   File "main.py", line 14, in main
    onResponse(argv[1])
    ~~~~~~~~~~^^^^^^^^^
  File "main.py", line 35, in onResponse
    result = addons.onResponse(context, CaptureHttpResponse(data['response']))
  File "addons.py", line 8, in onResponse
    for question in response.body['examVO']['questions']:
                    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by qimu666** [comment]
脚本已失效，官方改响应了
